[tool.poetry]
name = "python-gui-application-with-database-demo-for-sony"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
homepage = "https://github.com/FloTechnologies/uni-provisioner"

[tool.poetry.dependencies]
python = "~3.9"
dataset = "^1.4.5"
PySide6 = "^6.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
